/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDashboardResponse200StatsNewUsers } from './adminDashboardResponse200StatsNewUsers';
import type { AdminDashboardResponse200StatsSubscriptionRenewals } from './adminDashboardResponse200StatsSubscriptionRenewals';
import type { AdminDashboardResponse200StatsMonthlyRevenue } from './adminDashboardResponse200StatsMonthlyRevenue';
import type { AdminDashboardResponse200StatsActiveRentals } from './adminDashboardResponse200StatsActiveRentals';

export type AdminDashboardResponse200Stats = {
  newUsers?: AdminDashboardResponse200StatsNewUsers;
  subscriptionRenewals?: AdminDashboardResponse200StatsSubscriptionRenewals;
  monthlyRevenue?: AdminDashboardResponse200StatsMonthlyRevenue;
  activeRentals?: AdminDashboardResponse200StatsActiveRentals;
};
