/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDashboardResponse200Stats } from './adminDashboardResponse200Stats';
import type { AdminDashboardResponse200RevenueHistoryItem } from './adminDashboardResponse200RevenueHistoryItem';

export interface AdminDashboardResponse200 {
  stats?: AdminDashboardResponse200Stats;
  revenueHistory?: AdminDashboardResponse200RevenueHistoryItem[];
}
