/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */

export interface AuthResponse200 {
  /** The token for the user */
  token: string;
  /** The role of the user */
  role: string;
}
