/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */

/**
 * Standard bad request response
 */
export interface BadRequestResponse {
  status?: string;
  message?: string;
}
