/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */

export type BrowseCarPostingParams = {
/**
 * Search term
 */
search?: string;
/**
 * Page number
 */
page?: number;
/**
 * Number of items per page
 */
rows?: number;
/**
 * Filter by car brands
 */
brands?: string[];
/**
 * Filter by car types
 */
types?: string[];
/**
 * Minimum price filter
 */
price_from?: number;
/**
 * Maximum price filter
 */
price_to?: number;
};
