/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */
import type { CarType } from './carType';
import type { CarFuelType } from './carFuelType';
import type { CarTransmission } from './carTransmission';

export interface Car {
  id?: number;
  user_company_id: number;
  brand: string;
  model: string;
  plate_number: string;
  color: string;
  type: CarType;
  /** @nullable */
  year?: string | null;
  fuel_type: CarFuelType;
  transmission: CarTransmission;
  /** @nullable */
  engine_capacity?: string | null;
  /** @nullable */
  engine_power?: string | null;
  /** @nullable */
  engine_torque?: string | null;
  /** @nullable */
  engine_type?: string | null;
  created_at?: string;
  updated_at?: string;
  image_url?: string;
  is_available?: boolean;
}
