/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */
import type { Car } from './car';
import type { CarPostingUserReaction } from './carPostingUserReaction';

export interface CarPosting {
  id?: number;
  car_id: number;
  car?: Car;
  start_date: string;
  end_date: string;
  description: string;
  price: number;
  force_enabled: boolean;
  /** @nullable */
  created_at?: string | null;
  /** @nullable */
  updated_at?: string | null;
  is_available?: boolean;
  /** */
  total_reactions?: number;
  /** @nullable */
  user_reaction?: CarPostingUserReaction;
  /** */
  total_comments?: number;
}
