/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */

export type CarRentalPaymentMethod = typeof CarRentalPaymentMethod[keyof typeof CarRentalPaymentMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CarRentalPaymentMethod = {
  cash: 'cash',
  online: 'online',
} as const;
