/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */
import type { CarPosting } from './carPosting';
import type { User } from './user';
import type { CarRentalRentalStatus } from './carRentalRentalStatus';
import type { CarRentalPaymentMethod } from './carRentalPaymentMethod';

export interface CarRental {
  id?: number;
  car_posting_id: number;
  car_posting?: CarPosting;
  user_id: number;
  user?: User;
  days: number;
  deposit: number;
  start_date: string;
  return_date: string;
  rental_status: CarRentalRentalStatus;
  payment_method: CarRentalPaymentMethod;
  /** @nullable */
  payment_reference: string | null;
  created_at?: string;
  updated_at?: string;
}
