/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */

export type CarRentalRentalStatus = typeof CarRentalRentalStatus[keyof typeof CarRentalRentalStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CarRentalRentalStatus = {
  pending: 'pending',
  confirmed: 'confirmed',
  cancelled: 'cancelled',
  completed: 'completed',
} as const;
