/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */
import type { CarPosting } from './carPosting';
import type { User } from './user';
import type { CarRentalRentalStatus } from './carRentalRentalStatus';
import type { CarRentalPaymentMethod } from './carRentalPaymentMethod';

export interface CarRental {
  id?: number;
  car_posting_id: number;
  car_posting?: CarPosting;
  user_id: number;
  user?: User;
  days: number;
  deposit: number;
  start_date: string;
  /** @nullable */
  return_date: string | null;
  rental_status: CarRentalRentalStatus;
  /** @nullable */
  payment_method: CarRentalPaymentMethod;
  /** @nullable */
  payment_reference: string | null;
  /** Computed refundable amount based on rental status and return timing. */
  refundable_amount?: number;
  /** Computed additional charges, e.g., late return penalties. */
  additional_charges?: number;
  /**
   * Outstanding cash owed by the renter. Set when confirmed with cash payment; null for online or unsettled.
   * @nullable
   */
  cash_debt?: number | null;
  /** Whether the cash debt has been collected. */
  cash_debt_settled?: boolean;
  created_at?: string;
  updated_at?: string;
}
