/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */
import type { CheckCarPostingSubmission200Data } from './checkCarPostingSubmission200Data';

export type CheckCarPostingSubmission200 = {
  status?: string;
  data?: CheckCarPostingSubmission200Data;
};
