/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */

export interface Comment {
  id: number;
  content: string;
  user_id: number;
  post_id: number;
  /** @nullable */
  parent_id?: number | null;
  created_at: string;
  updated_at: string;
}
