/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */
import type { CommentUser } from './commentUser';

export interface Comment {
  id: number;
  comment?: string;
  user_id: number;
  car_posting_id: number;
  /** @nullable */
  parent_comment_id?: number | null;
  created_at: string;
  updated_at: string;
  /** @nullable */
  user?: CommentUser;
  is_current_user?: boolean;
  /** @nullable */
  replies?: Comment[] | null;
}
