/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */
import type { CreateCarBodyType } from './createCarBodyType';
import type { CreateCarBodyFuelType } from './createCarBodyFuelType';
import type { CreateCarBodyTransmission } from './createCarBodyTransmission';

export type CreateCarBody = {
  id?: number;
  user_company_id: number;
  brand: string;
  model: string;
  plate_number: string;
  color: string;
  type: CreateCarBodyType;
  /** @nullable */
  year?: string | null;
  fuel_type: CreateCarBodyFuelType;
  transmission: CreateCarBodyTransmission;
  /** @nullable */
  engine_capacity?: string | null;
  /** @nullable */
  engine_power?: string | null;
  /** @nullable */
  engine_torque?: string | null;
  /** @nullable */
  engine_type?: string | null;
  created_at?: string;
  updated_at?: string;
  /** Car images */
  images?: Blob[];
};
