/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */

export interface DeviceLocation {
  readonly id?: number;
  latitude: number;
  longitude: number;
  device_id: number;
  readonly created_at?: string;
  readonly updated_at?: string;
}
