/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */

export interface Device {
  readonly id?: number;
  device_identifier: string;
  car_rental_id: number;
  readonly created_at?: string;
  readonly updated_at?: string;
}
