/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */
import type { DeviceWithLocationsLatestLocation } from './deviceWithLocationsLatestLocation';
import type { DeviceLocation } from './deviceLocation';

export interface DeviceWithLocations {
  readonly id?: number;
  device_identifier?: string;
  car_rental_id?: number;
  /** @nullable */
  latest_location?: DeviceWithLocationsLatestLocation;
  locations?: DeviceLocation[];
  readonly created_at?: string;
  readonly updated_at?: string;
}
