/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */
import type { CarRental } from './carRental';
import type { FinishCarRentalResponse200DataRefundTransaction } from './finishCarRentalResponse200DataRefundTransaction';
import type { FinishCarRentalResponse200DataPayoutAccount } from './finishCarRentalResponse200DataPayoutAccount';

export type FinishCarRentalResponse200Data = {
  rental?: CarRental;
  refundable_amount?: number;
  additional_charges?: number;
  /** @nullable */
  refund_transaction?: FinishCarRentalResponse200DataRefundTransaction;
  /** @nullable */
  stripe_refund_id?: string | null;
  /** @nullable */
  payout_account?: FinishCarRentalResponse200DataPayoutAccount;
};
