/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */

export type GetCarPostingPaginatedStatus = typeof GetCarPostingPaginatedStatus[keyof typeof GetCarPostingPaginatedStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCarPostingPaginatedStatus = {
  all: 'all',
  active: 'active',
  expired: 'expired',
} as const;
