/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */
import type { GetCarPostingPaginatedStatus } from './getCarPostingPaginatedStatus';

export type GetCarPostingPaginatedParams = {
/**
 * Search term
 */
search?: string;
/**
 * Page number
 */
page?: number;
/**
 * Number of items per page
 */
rows?: number;
/**
 * Company ID
 */
company_id?: number;
/**
 * Is available
 */
is_available?: boolean;
/**
 * Posting status filter: one of 'all', 'active', 'expired'
 */
status?: GetCarPostingPaginatedStatus;
};
