/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */

export type GetMachineInfo200 = {
  /** Detailed Operating System version string */
  HOSTOS: string;
  /** Total available system RAM in MB */
  TotalRam: number;
  /** Currently free/available RAM in MB */
  AvailableRam: number;
  /** Processor manufacturer or brand string */
  CpuVendor: string;
  /** Specific marketing model of the processor */
  CpuModel: string;
  /** Processor maximum or current clock speed */
  CpuSpeed: string;
  /** Current CPU utilization percentage */
  CpuUtilization: number;
};
