/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * APX API
 * API documentation for the APEX application
 * OpenAPI spec version: 1.0.0
 */
import type { Plan } from './plan';

export interface GetPlanPlanResponse200 {
  success?: boolean;
  data?: Plan;
}
