/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */
import type { GetUserAccountPaginatedType } from './getUserAccountPaginatedType';

export type GetUserAccountPaginatedParams = {
/**
 * Search term for account number
 */
search?: string;
/**
 * Filter by account type
 */
type?: GetUserAccountPaginatedType;
/**
 * Page number
 */
page?: number;
/**
 * Number of items per page
 */
rows?: number;
/**
 * When true, only return accounts for authenticated user
 */
current_user?: boolean;
};
