/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */
import type { GetUserDashboard200StatsActiveBookings } from './getUserDashboard200StatsActiveBookings';
import type { GetUserDashboard200StatsTotalTrips } from './getUserDashboard200StatsTotalTrips';
import type { GetUserDashboard200StatsTotalSpent } from './getUserDashboard200StatsTotalSpent';
import type { GetUserDashboard200StatsAvgRating } from './getUserDashboard200StatsAvgRating';

export type GetUserDashboard200Stats = {
  activeBookings?: GetUserDashboard200StatsActiveBookings;
  totalTrips?: GetUserDashboard200StatsTotalTrips;
  totalSpent?: GetUserDashboard200StatsTotalSpent;
  avgRating?: GetUserDashboard200StatsAvgRating;
};
