/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */
import type { GetUserDashboard200Stats } from './getUserDashboard200Stats';
import type { CarRental } from './carRental';
import type { GetUserDashboard200RevenueHistoryItem } from './getUserDashboard200RevenueHistoryItem';
import type { GetUserDashboard200RecentActivityItem } from './getUserDashboard200RecentActivityItem';

export type GetUserDashboard200 = {
  stats?: GetUserDashboard200Stats;
  activeBookings?: CarRental[];
  revenueHistory?: GetUserDashboard200RevenueHistoryItem[];
  recentActivity?: GetUserDashboard200RecentActivityItem[];
};
