/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */

export interface LoginRequest {
  /** The email of the user */
  email: string;
  /** The password of the user */
  password: string;
}
