/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */
import type { NotFoundResponse } from './notFoundResponse';

/**
 * Not found
 */
export type N404Response = NotFoundResponse;
