/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */
import type { UserCompany } from './userCompany';

export interface PaginatedUserCompany {
  data?: UserCompany[];
  current_page?: number;
  last_page?: number;
  per_page?: number;
  total?: number;
  /** @nullable */
  from?: number | null;
  /** @nullable */
  to?: number | null;
}
