/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedCar } from './paginatedCar';

export interface PaginatedCarResponse200 {
  success?: boolean;
  data?: PaginatedCar;
}
