/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedDeviceLocation } from './paginatedDeviceLocation';

export interface PaginatedDeviceLocationResponse200 {
  success?: boolean;
  data?: PaginatedDeviceLocation;
}
