/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedUserRequirement } from './paginatedUserRequirement';

export interface PaginatedUserRequirementResponse200 {
  success?: boolean;
  data?: PaginatedUserRequirement;
}
