/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */

export interface PlanFeature {
  id: number;
  plan_id?: number;
  name: string;
  value: string;
  created_at?: string;
  updated_at?: string;
}
