/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */

export interface Reaction {
  id?: number;
  car_posting_id: number;
  user_id: number;
  reaction: string;
  created_at?: string;
  updated_at?: string;
}
