/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */

export type RequirementRole = typeof RequirementRole[keyof typeof RequirementRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RequirementRole = {
  admin: 'admin',
  user: 'user',
  renter: 'renter',
} as const;
