/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */

export interface Requirement {
  id?: number;
  created_at?: string;
  updated_at?: string;
  name: string;
  description: string;
  is_required: boolean;
  is_active: boolean;
  role: string;
}
