/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */

export interface SignupRequest {
  /** The first name of the user */
  firstname?: string;
  /** The last name of the user */
  lastname?: string;
  /** The username of the user */
  username?: string;
  /**
   * The phone number of the user
   * @nullable
   */
  phone?: string | null;
  /**
   * The country of the user
   * @nullable
   */
  country?: string | null;
  /**
   * The city of the user
   * @nullable
   */
  city?: string | null;
  /**
   * The address of the user
   * @nullable
   */
  address?: string | null;
  /**
   * The postal code of the user
   * @nullable
   */
  postal_code?: string | null;
  /** The email of the user */
  email: string;
  /** The password of the user */
  password: string;
  /** The password confirmation of the user */
  password_confirmation: string;
}
