/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */

export type SubscribeToplanBody = {
  plan_id: number;
  success_url: string;
  cancel_url: string;
};
