/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */
import type { SuccessResponseData } from './successResponseData';

/**
 * Standard success response
 */
export interface SuccessResponse {
  status?: string;
  /**
   * The data returned by the API
   * @nullable
   */
  data?: SuccessResponseData;
}
