/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */

/**
 * The data returned by the API
 * @nullable
 */
export type SuccessResponseData = { [key: string]: unknown } | null;
