/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */

export type UpdateCarBodyType = typeof UpdateCarBodyType[keyof typeof UpdateCarBodyType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateCarBodyType = {
  sedan: 'sedan',
  hatchback: 'hatchback',
  suv: 'suv',
  mpv: 'mpv',
  coupe: 'coupe',
  convertible: 'convertible',
  other: 'other',
} as const;
