/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */

export type UpdateCarBodyTransmission = typeof UpdateCarBodyTransmission[keyof typeof UpdateCarBodyTransmission];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateCarBodyTransmission = {
  manual: 'manual',
  automatic: 'automatic',
  other: 'other',
} as const;
