/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */

export type UpdateCarBodyFuelType = typeof UpdateCarBodyFuelType[keyof typeof UpdateCarBodyFuelType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateCarBodyFuelType = {
  petrol: 'petrol',
  diesel: 'diesel',
  electric: 'electric',
  hybrid: 'hybrid',
  other: 'other',
} as const;
