/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */

export type UploadProfilePicture200 = {
  success?: boolean;
  message?: string;
  /** URL of the uploaded profile picture */
  data?: string;
};
