/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */
import type { Requirement } from './requirement';
import type { User } from './user';
import type { Media } from './media';

export interface UserRequirement {
  id?: number;
  user_id: number;
  requirement_id: number;
  created_at?: string;
  updated_at?: string;
  requirement?: Requirement;
  user?: User;
  uploads?: Media;
}
