/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */
import type { UserRequirementResponse200DataItemMediaItem } from './userRequirementResponse200DataItemMediaItem';

export type UserRequirementResponse200DataItem = {
  /** @nullable */
  id?: number | null;
  /** @nullable */
  created_at?: string | null;
  /** @nullable */
  updated_at?: string | null;
  name?: string;
  description?: string;
  is_required?: number;
  is_active?: number;
  role?: unknown;
  /** @nullable */
  user_id?: number | null;
  /** @nullable */
  requirement_id?: number | null;
  media?: UserRequirementResponse200DataItemMediaItem[];
};
