/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */
import type { User } from './user';

export interface UserCompany {
  id?: number;
  user_id: number;
  name: string;
  address: string;
  city: string;
  country: string;
  postal_code: string;
  opening_time: string;
  closing_time: string;
  days_open?: string;
  created_at?: string;
  updated_at?: string;
  owner?: User;
}
