/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */

export interface UserSubscription {
  id: number;
  user_id: number;
  plan_id: number;
  created_at?: string;
  updated_at?: string;
}
