/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */

export type UserRequirementResponse200Data = {
  /** @nullable */
  id?: number | null;
  /** @nullable */
  created_at?: string | null;
  /** @nullable */
  updated_at?: string | null;
  name?: string;
  description?: string;
  is_required?: number;
  is_active?: number;
  role?: string;
  /** @nullable */
  user_id?: number | null;
  /** @nullable */
  requirement_id?: number | null;
};
