/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */

export type UserAccountType = typeof UserAccountType[keyof typeof UserAccountType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserAccountType = {
  GCash: 'GCash',
  Maya: 'Maya',
  Bank: 'Bank',
} as const;
