/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */

export type UserRequirementResponse200DataItemRole = typeof UserRequirementResponse200DataItemRole[keyof typeof UserRequirementResponse200DataItemRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRequirementResponse200DataItemRole = {
  admin: 'admin',
  user: 'user',
  renter: 'renter',
} as const;
