/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */
import type { UserRole } from './userRole';

export interface User {
  id: number;
  firstname: string;
  lastname: string;
  username: string;
  phone: string;
  country: string;
  city: string;
  address: string;
  postal_code: string;
  email: string;
  role: UserRole;
  is_active: boolean;
  name?: string;
  profile_picture?: string;
}
