/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */

export type UserRequirementResponse200DataItemMediaItem = {
  id?: number;
  file_name?: string;
  mime_type?: string;
  size?: number;
  url?: string;
};
