/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */
import type { UserAccountType } from './userAccountType';
import type { User } from './user';

export interface UserAccount {
  id?: number;
  user_id: number;
  type: UserAccountType;
  account_number: string;
  is_default?: boolean;
  created_at?: string;
  updated_at?: string;
  owner?: User;
}
