/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */
import type { UserRequirementResponse200DataItem } from './userRequirementResponse200DataItem';

export interface UserRequirementResponse200 {
  success?: boolean;
  data?: UserRequirementResponse200DataItem[];
}
