/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Geocars API
 * API documentation for the Geocars application
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthResponse200,
  CreatePlanFeatureResponse200,
  CreatePlanResponse200,
  CreateUserCompanyResponse200,
  CreateUserResponse200,
  DeletePlanFeatureResponse200,
  DeletePlanResponse200,
  DeleteUserCompanyResponse200,
  DeleteUserResponse200,
  GetPlanFeaturePaginatedParams,
  GetPlanFeatureResponse200,
  GetPlanResponse200,
  GetPlansPaginatedParams,
  GetUserCompanyPaginatedParams,
  GetUserCompanyResponse200,
  GetUserPaginatedParams,
  GetUserResponse200,
  InternalServerErrorResponse,
  LoginRequest,
  NotFoundResponse,
  PaginatedPlanFeatureResponse200,
  PaginatedPlanResponse200,
  PaginatedUserCompanyResponse200,
  PaginatedUserResponse200,
  Plan,
  PlanFeature,
  UpdatePlanFeatureResponse200,
  UpdatePlanResponse200,
  UpdateUserCompanyResponse200,
  UpdateUserResponse200,
  User,
  UserCompany,
  ValidationErrorResponse
} from './models';

import { fetchData } from './axios';
/**
 *  Login with the provided details
 * @summary Login
 */
export const loginWithCredentials = (
    loginRequest: LoginRequest,
 signal?: AbortSignal
) => {
      
      
      return fetchData<AuthResponse200>(
      {url: `/api/Auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest, signal
    },
      );
    }
  


export const getLoginWithCredentialsMutationOptions = <TError = ValidationErrorResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginWithCredentials>>, TError,{data: LoginRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof loginWithCredentials>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['loginWithCredentials'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginWithCredentials>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  loginWithCredentials(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginWithCredentialsMutationResult = NonNullable<Awaited<ReturnType<typeof loginWithCredentials>>>
    export type LoginWithCredentialsMutationBody = LoginRequest
    export type LoginWithCredentialsMutationError = ValidationErrorResponse | InternalServerErrorResponse

    /**
 * @summary Login
 */
export const useLoginWithCredentials = <TError = ValidationErrorResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginWithCredentials>>, TError,{data: LoginRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginWithCredentials>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {

      const mutationOptions = getLoginWithCredentialsMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Retrieve a paginated list of plans with optional search
 * @summary Get paginated list of plans
 */
export const getPlansPaginated = (
    params?: GetPlansPaginatedParams,
 signal?: AbortSignal
) => {
      
      
      return fetchData<PaginatedPlanResponse200>(
      {url: `/api/Plan`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetPlansPaginatedQueryKey = (params?: GetPlansPaginatedParams,) => {
    return [`/api/Plan`, ...(params ? [params]: [])] as const;
    }

    
export const getGetPlansPaginatedQueryOptions = <TData = Awaited<ReturnType<typeof getPlansPaginated>>, TError = unknown>(params?: GetPlansPaginatedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlansPaginated>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPlansPaginatedQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlansPaginated>>> = ({ signal }) => getPlansPaginated(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPlansPaginated>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPlansPaginatedQueryResult = NonNullable<Awaited<ReturnType<typeof getPlansPaginated>>>
export type GetPlansPaginatedQueryError = unknown


export function useGetPlansPaginated<TData = Awaited<ReturnType<typeof getPlansPaginated>>, TError = unknown>(
 params: undefined |  GetPlansPaginatedParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlansPaginated>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlansPaginated>>,
          TError,
          Awaited<ReturnType<typeof getPlansPaginated>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPlansPaginated<TData = Awaited<ReturnType<typeof getPlansPaginated>>, TError = unknown>(
 params?: GetPlansPaginatedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlansPaginated>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlansPaginated>>,
          TError,
          Awaited<ReturnType<typeof getPlansPaginated>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPlansPaginated<TData = Awaited<ReturnType<typeof getPlansPaginated>>, TError = unknown>(
 params?: GetPlansPaginatedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlansPaginated>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get paginated list of plans
 */

export function useGetPlansPaginated<TData = Awaited<ReturnType<typeof getPlansPaginated>>, TError = unknown>(
 params?: GetPlansPaginatedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlansPaginated>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPlansPaginatedQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 *  Create a new plan with the provided details
 * @summary Create a new plan
 */
export const createPlan = (
    plan: Plan,
 signal?: AbortSignal
) => {
      
      
      return fetchData<CreatePlanResponse200>(
      {url: `/api/Plan`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: plan, signal
    },
      );
    }
  


export const getCreatePlanMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPlan>>, TError,{data: Plan}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createPlan>>, TError,{data: Plan}, TContext> => {

const mutationKey = ['createPlan'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPlan>>, {data: Plan}> = (props) => {
          const {data} = props ?? {};

          return  createPlan(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePlanMutationResult = NonNullable<Awaited<ReturnType<typeof createPlan>>>
    export type CreatePlanMutationBody = Plan
    export type CreatePlanMutationError = unknown

    /**
 * @summary Create a new plan
 */
export const useCreatePlan = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPlan>>, TError,{data: Plan}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPlan>>,
        TError,
        {data: Plan},
        TContext
      > => {

      const mutationOptions = getCreatePlanMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Retrieve a plan by its ID
 * @summary Get a specific plan
 */
export const getPlanById = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return fetchData<GetPlanResponse200>(
      {url: `/api/Plan/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getGetPlanByIdQueryKey = (id?: number,) => {
    return [`/api/Plan/${id}`] as const;
    }

    
export const getGetPlanByIdQueryOptions = <TData = Awaited<ReturnType<typeof getPlanById>>, TError = null>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlanById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPlanByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlanById>>> = ({ signal }) => getPlanById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPlanById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPlanByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getPlanById>>>
export type GetPlanByIdQueryError = null


export function useGetPlanById<TData = Awaited<ReturnType<typeof getPlanById>>, TError = null>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlanById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlanById>>,
          TError,
          Awaited<ReturnType<typeof getPlanById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPlanById<TData = Awaited<ReturnType<typeof getPlanById>>, TError = null>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlanById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlanById>>,
          TError,
          Awaited<ReturnType<typeof getPlanById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPlanById<TData = Awaited<ReturnType<typeof getPlanById>>, TError = null>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlanById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a specific plan
 */

export function useGetPlanById<TData = Awaited<ReturnType<typeof getPlanById>>, TError = null>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlanById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPlanByIdQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Update an existing plan with the provided details
 * @summary Update a plan
 */
export const updatePlan = (
    id: number,
    plan: Plan,
 ) => {
      
      
      return fetchData<UpdatePlanResponse200>(
      {url: `/api/Plan/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: plan
    },
      );
    }
  


export const getUpdatePlanMutationOptions = <TError = NotFoundResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePlan>>, TError,{id: number;data: Plan}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updatePlan>>, TError,{id: number;data: Plan}, TContext> => {

const mutationKey = ['updatePlan'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePlan>>, {id: number;data: Plan}> = (props) => {
          const {id,data} = props ?? {};

          return  updatePlan(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePlanMutationResult = NonNullable<Awaited<ReturnType<typeof updatePlan>>>
    export type UpdatePlanMutationBody = Plan
    export type UpdatePlanMutationError = NotFoundResponse

    /**
 * @summary Update a plan
 */
export const useUpdatePlan = <TError = NotFoundResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePlan>>, TError,{id: number;data: Plan}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePlan>>,
        TError,
        {id: number;data: Plan},
        TContext
      > => {

      const mutationOptions = getUpdatePlanMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Delete a plan by its ID
 * @summary Delete a plan
 */
export const deletePlan = (
    id: number,
 ) => {
      
      
      return fetchData<DeletePlanResponse200>(
      {url: `/api/Plan/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeletePlanMutationOptions = <TError = NotFoundResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePlan>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deletePlan>>, TError,{id: number}, TContext> => {

const mutationKey = ['deletePlan'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePlan>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deletePlan(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeletePlanMutationResult = NonNullable<Awaited<ReturnType<typeof deletePlan>>>
    
    export type DeletePlanMutationError = NotFoundResponse

    /**
 * @summary Delete a plan
 */
export const useDeletePlan = <TError = NotFoundResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePlan>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePlan>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeletePlanMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Retrieve a paginated list of PlanFeature with optional search
 * @summary Get paginated list of PlanFeature
 */
export const getPlanFeaturePaginated = (
    params?: GetPlanFeaturePaginatedParams,
 signal?: AbortSignal
) => {
      
      
      return fetchData<PaginatedPlanFeatureResponse200>(
      {url: `/api/PlanFeature`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetPlanFeaturePaginatedQueryKey = (params?: GetPlanFeaturePaginatedParams,) => {
    return [`/api/PlanFeature`, ...(params ? [params]: [])] as const;
    }

    
export const getGetPlanFeaturePaginatedQueryOptions = <TData = Awaited<ReturnType<typeof getPlanFeaturePaginated>>, TError = unknown>(params?: GetPlanFeaturePaginatedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlanFeaturePaginated>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPlanFeaturePaginatedQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlanFeaturePaginated>>> = ({ signal }) => getPlanFeaturePaginated(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPlanFeaturePaginated>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPlanFeaturePaginatedQueryResult = NonNullable<Awaited<ReturnType<typeof getPlanFeaturePaginated>>>
export type GetPlanFeaturePaginatedQueryError = unknown


export function useGetPlanFeaturePaginated<TData = Awaited<ReturnType<typeof getPlanFeaturePaginated>>, TError = unknown>(
 params: undefined |  GetPlanFeaturePaginatedParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlanFeaturePaginated>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlanFeaturePaginated>>,
          TError,
          Awaited<ReturnType<typeof getPlanFeaturePaginated>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPlanFeaturePaginated<TData = Awaited<ReturnType<typeof getPlanFeaturePaginated>>, TError = unknown>(
 params?: GetPlanFeaturePaginatedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlanFeaturePaginated>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlanFeaturePaginated>>,
          TError,
          Awaited<ReturnType<typeof getPlanFeaturePaginated>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPlanFeaturePaginated<TData = Awaited<ReturnType<typeof getPlanFeaturePaginated>>, TError = unknown>(
 params?: GetPlanFeaturePaginatedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlanFeaturePaginated>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get paginated list of PlanFeature
 */

export function useGetPlanFeaturePaginated<TData = Awaited<ReturnType<typeof getPlanFeaturePaginated>>, TError = unknown>(
 params?: GetPlanFeaturePaginatedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlanFeaturePaginated>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPlanFeaturePaginatedQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 *  Create a new PlanFeature with the provided details
 * @summary Create a new PlanFeature
 */
export const createPlanFeature = (
    planFeature: PlanFeature,
 signal?: AbortSignal
) => {
      
      
      return fetchData<CreatePlanFeatureResponse200>(
      {url: `/api/PlanFeature`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: planFeature, signal
    },
      );
    }
  


export const getCreatePlanFeatureMutationOptions = <TError = ValidationErrorResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPlanFeature>>, TError,{data: PlanFeature}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createPlanFeature>>, TError,{data: PlanFeature}, TContext> => {

const mutationKey = ['createPlanFeature'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPlanFeature>>, {data: PlanFeature}> = (props) => {
          const {data} = props ?? {};

          return  createPlanFeature(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePlanFeatureMutationResult = NonNullable<Awaited<ReturnType<typeof createPlanFeature>>>
    export type CreatePlanFeatureMutationBody = PlanFeature
    export type CreatePlanFeatureMutationError = ValidationErrorResponse | InternalServerErrorResponse

    /**
 * @summary Create a new PlanFeature
 */
export const useCreatePlanFeature = <TError = ValidationErrorResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPlanFeature>>, TError,{data: PlanFeature}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPlanFeature>>,
        TError,
        {data: PlanFeature},
        TContext
      > => {

      const mutationOptions = getCreatePlanFeatureMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Retrieve a PlanFeature by its ID
 * @summary Get a specific PlanFeature
 */
export const getPlanFeatureById = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return fetchData<GetPlanFeatureResponse200>(
      {url: `/api/PlanFeature/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getGetPlanFeatureByIdQueryKey = (id?: number,) => {
    return [`/api/PlanFeature/${id}`] as const;
    }

    
export const getGetPlanFeatureByIdQueryOptions = <TData = Awaited<ReturnType<typeof getPlanFeatureById>>, TError = null>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlanFeatureById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPlanFeatureByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlanFeatureById>>> = ({ signal }) => getPlanFeatureById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPlanFeatureById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPlanFeatureByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getPlanFeatureById>>>
export type GetPlanFeatureByIdQueryError = null


export function useGetPlanFeatureById<TData = Awaited<ReturnType<typeof getPlanFeatureById>>, TError = null>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlanFeatureById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlanFeatureById>>,
          TError,
          Awaited<ReturnType<typeof getPlanFeatureById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPlanFeatureById<TData = Awaited<ReturnType<typeof getPlanFeatureById>>, TError = null>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlanFeatureById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlanFeatureById>>,
          TError,
          Awaited<ReturnType<typeof getPlanFeatureById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPlanFeatureById<TData = Awaited<ReturnType<typeof getPlanFeatureById>>, TError = null>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlanFeatureById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a specific PlanFeature
 */

export function useGetPlanFeatureById<TData = Awaited<ReturnType<typeof getPlanFeatureById>>, TError = null>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlanFeatureById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPlanFeatureByIdQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Update an existing PlanFeature with the provided details
 * @summary Update a PlanFeature
 */
export const updatePlanFeature = (
    id: number,
    planFeature: PlanFeature,
 ) => {
      
      
      return fetchData<UpdatePlanFeatureResponse200>(
      {url: `/api/PlanFeature/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: planFeature
    },
      );
    }
  


export const getUpdatePlanFeatureMutationOptions = <TError = null | ValidationErrorResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePlanFeature>>, TError,{id: number;data: PlanFeature}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updatePlanFeature>>, TError,{id: number;data: PlanFeature}, TContext> => {

const mutationKey = ['updatePlanFeature'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePlanFeature>>, {id: number;data: PlanFeature}> = (props) => {
          const {id,data} = props ?? {};

          return  updatePlanFeature(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePlanFeatureMutationResult = NonNullable<Awaited<ReturnType<typeof updatePlanFeature>>>
    export type UpdatePlanFeatureMutationBody = PlanFeature
    export type UpdatePlanFeatureMutationError = null | ValidationErrorResponse | InternalServerErrorResponse

    /**
 * @summary Update a PlanFeature
 */
export const useUpdatePlanFeature = <TError = null | ValidationErrorResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePlanFeature>>, TError,{id: number;data: PlanFeature}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePlanFeature>>,
        TError,
        {id: number;data: PlanFeature},
        TContext
      > => {

      const mutationOptions = getUpdatePlanFeatureMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Delete a PlanFeature by its ID
 * @summary Delete a PlanFeature
 */
export const deletePlanFeature = (
    id: number,
 ) => {
      
      
      return fetchData<DeletePlanFeatureResponse200>(
      {url: `/api/PlanFeature/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeletePlanFeatureMutationOptions = <TError = null | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePlanFeature>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deletePlanFeature>>, TError,{id: number}, TContext> => {

const mutationKey = ['deletePlanFeature'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePlanFeature>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deletePlanFeature(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeletePlanFeatureMutationResult = NonNullable<Awaited<ReturnType<typeof deletePlanFeature>>>
    
    export type DeletePlanFeatureMutationError = null | InternalServerErrorResponse

    /**
 * @summary Delete a PlanFeature
 */
export const useDeletePlanFeature = <TError = null | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePlanFeature>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePlanFeature>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeletePlanFeatureMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Retrieve a paginated list of UserCompany with optional search
 * @summary Get paginated list of UserCompany
 */
export const getUserCompanyPaginated = (
    params?: GetUserCompanyPaginatedParams,
 signal?: AbortSignal
) => {
      
      
      return fetchData<PaginatedUserCompanyResponse200>(
      {url: `/api/UserCompany`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetUserCompanyPaginatedQueryKey = (params?: GetUserCompanyPaginatedParams,) => {
    return [`/api/UserCompany`, ...(params ? [params]: [])] as const;
    }

    
export const getGetUserCompanyPaginatedQueryOptions = <TData = Awaited<ReturnType<typeof getUserCompanyPaginated>>, TError = unknown>(params?: GetUserCompanyPaginatedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserCompanyPaginated>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserCompanyPaginatedQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserCompanyPaginated>>> = ({ signal }) => getUserCompanyPaginated(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserCompanyPaginated>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserCompanyPaginatedQueryResult = NonNullable<Awaited<ReturnType<typeof getUserCompanyPaginated>>>
export type GetUserCompanyPaginatedQueryError = unknown


export function useGetUserCompanyPaginated<TData = Awaited<ReturnType<typeof getUserCompanyPaginated>>, TError = unknown>(
 params: undefined |  GetUserCompanyPaginatedParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserCompanyPaginated>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserCompanyPaginated>>,
          TError,
          Awaited<ReturnType<typeof getUserCompanyPaginated>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserCompanyPaginated<TData = Awaited<ReturnType<typeof getUserCompanyPaginated>>, TError = unknown>(
 params?: GetUserCompanyPaginatedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserCompanyPaginated>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserCompanyPaginated>>,
          TError,
          Awaited<ReturnType<typeof getUserCompanyPaginated>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserCompanyPaginated<TData = Awaited<ReturnType<typeof getUserCompanyPaginated>>, TError = unknown>(
 params?: GetUserCompanyPaginatedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserCompanyPaginated>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get paginated list of UserCompany
 */

export function useGetUserCompanyPaginated<TData = Awaited<ReturnType<typeof getUserCompanyPaginated>>, TError = unknown>(
 params?: GetUserCompanyPaginatedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserCompanyPaginated>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserCompanyPaginatedQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 *  Create a new UserCompany with the provided details
 * @summary Create a new UserCompany
 */
export const createUserCompany = (
    userCompany: UserCompany,
 signal?: AbortSignal
) => {
      
      
      return fetchData<CreateUserCompanyResponse200>(
      {url: `/api/UserCompany`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userCompany, signal
    },
      );
    }
  


export const getCreateUserCompanyMutationOptions = <TError = ValidationErrorResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUserCompany>>, TError,{data: UserCompany}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createUserCompany>>, TError,{data: UserCompany}, TContext> => {

const mutationKey = ['createUserCompany'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createUserCompany>>, {data: UserCompany}> = (props) => {
          const {data} = props ?? {};

          return  createUserCompany(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateUserCompanyMutationResult = NonNullable<Awaited<ReturnType<typeof createUserCompany>>>
    export type CreateUserCompanyMutationBody = UserCompany
    export type CreateUserCompanyMutationError = ValidationErrorResponse | InternalServerErrorResponse

    /**
 * @summary Create a new UserCompany
 */
export const useCreateUserCompany = <TError = ValidationErrorResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUserCompany>>, TError,{data: UserCompany}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createUserCompany>>,
        TError,
        {data: UserCompany},
        TContext
      > => {

      const mutationOptions = getCreateUserCompanyMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Retrieve a UserCompany by its ID
 * @summary Get a specific UserCompany
 */
export const getUserCompanyById = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return fetchData<GetUserCompanyResponse200>(
      {url: `/api/UserCompany/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getGetUserCompanyByIdQueryKey = (id?: number,) => {
    return [`/api/UserCompany/${id}`] as const;
    }

    
export const getGetUserCompanyByIdQueryOptions = <TData = Awaited<ReturnType<typeof getUserCompanyById>>, TError = null>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserCompanyById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserCompanyByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserCompanyById>>> = ({ signal }) => getUserCompanyById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserCompanyById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserCompanyByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getUserCompanyById>>>
export type GetUserCompanyByIdQueryError = null


export function useGetUserCompanyById<TData = Awaited<ReturnType<typeof getUserCompanyById>>, TError = null>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserCompanyById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserCompanyById>>,
          TError,
          Awaited<ReturnType<typeof getUserCompanyById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserCompanyById<TData = Awaited<ReturnType<typeof getUserCompanyById>>, TError = null>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserCompanyById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserCompanyById>>,
          TError,
          Awaited<ReturnType<typeof getUserCompanyById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserCompanyById<TData = Awaited<ReturnType<typeof getUserCompanyById>>, TError = null>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserCompanyById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a specific UserCompany
 */

export function useGetUserCompanyById<TData = Awaited<ReturnType<typeof getUserCompanyById>>, TError = null>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserCompanyById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserCompanyByIdQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Update an existing UserCompany with the provided details
 * @summary Update a UserCompany
 */
export const updateUserCompany = (
    id: number,
    userCompany: UserCompany,
 ) => {
      
      
      return fetchData<UpdateUserCompanyResponse200>(
      {url: `/api/UserCompany/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: userCompany
    },
      );
    }
  


export const getUpdateUserCompanyMutationOptions = <TError = null | ValidationErrorResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserCompany>>, TError,{id: number;data: UserCompany}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateUserCompany>>, TError,{id: number;data: UserCompany}, TContext> => {

const mutationKey = ['updateUserCompany'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUserCompany>>, {id: number;data: UserCompany}> = (props) => {
          const {id,data} = props ?? {};

          return  updateUserCompany(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUserCompanyMutationResult = NonNullable<Awaited<ReturnType<typeof updateUserCompany>>>
    export type UpdateUserCompanyMutationBody = UserCompany
    export type UpdateUserCompanyMutationError = null | ValidationErrorResponse | InternalServerErrorResponse

    /**
 * @summary Update a UserCompany
 */
export const useUpdateUserCompany = <TError = null | ValidationErrorResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserCompany>>, TError,{id: number;data: UserCompany}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateUserCompany>>,
        TError,
        {id: number;data: UserCompany},
        TContext
      > => {

      const mutationOptions = getUpdateUserCompanyMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Delete a UserCompany by its ID
 * @summary Delete a UserCompany
 */
export const deleteUserCompany = (
    id: number,
 ) => {
      
      
      return fetchData<DeleteUserCompanyResponse200>(
      {url: `/api/UserCompany/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteUserCompanyMutationOptions = <TError = null | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUserCompany>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteUserCompany>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteUserCompany'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUserCompany>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteUserCompany(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserCompanyMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUserCompany>>>
    
    export type DeleteUserCompanyMutationError = null | InternalServerErrorResponse

    /**
 * @summary Delete a UserCompany
 */
export const useDeleteUserCompany = <TError = null | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUserCompany>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUserCompany>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteUserCompanyMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Retrieve a paginated list of User with optional search
 * @summary Get paginated list of User
 */
export const getUserPaginated = (
    params?: GetUserPaginatedParams,
 signal?: AbortSignal
) => {
      
      
      return fetchData<PaginatedUserResponse200>(
      {url: `/api/User`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetUserPaginatedQueryKey = (params?: GetUserPaginatedParams,) => {
    return [`/api/User`, ...(params ? [params]: [])] as const;
    }

    
export const getGetUserPaginatedQueryOptions = <TData = Awaited<ReturnType<typeof getUserPaginated>>, TError = unknown>(params?: GetUserPaginatedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserPaginated>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserPaginatedQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserPaginated>>> = ({ signal }) => getUserPaginated(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserPaginated>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserPaginatedQueryResult = NonNullable<Awaited<ReturnType<typeof getUserPaginated>>>
export type GetUserPaginatedQueryError = unknown


export function useGetUserPaginated<TData = Awaited<ReturnType<typeof getUserPaginated>>, TError = unknown>(
 params: undefined |  GetUserPaginatedParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserPaginated>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserPaginated>>,
          TError,
          Awaited<ReturnType<typeof getUserPaginated>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserPaginated<TData = Awaited<ReturnType<typeof getUserPaginated>>, TError = unknown>(
 params?: GetUserPaginatedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserPaginated>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserPaginated>>,
          TError,
          Awaited<ReturnType<typeof getUserPaginated>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserPaginated<TData = Awaited<ReturnType<typeof getUserPaginated>>, TError = unknown>(
 params?: GetUserPaginatedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserPaginated>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get paginated list of User
 */

export function useGetUserPaginated<TData = Awaited<ReturnType<typeof getUserPaginated>>, TError = unknown>(
 params?: GetUserPaginatedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserPaginated>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserPaginatedQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 *  Create a new User with the provided details
 * @summary Create a new User
 */
export const createUser = (
    user: User,
 signal?: AbortSignal
) => {
      
      
      return fetchData<CreateUserResponse200>(
      {url: `/api/User`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: user, signal
    },
      );
    }
  


export const getCreateUserMutationOptions = <TError = ValidationErrorResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{data: User}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{data: User}, TContext> => {

const mutationKey = ['createUser'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createUser>>, {data: User}> = (props) => {
          const {data} = props ?? {};

          return  createUser(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateUserMutationResult = NonNullable<Awaited<ReturnType<typeof createUser>>>
    export type CreateUserMutationBody = User
    export type CreateUserMutationError = ValidationErrorResponse | InternalServerErrorResponse

    /**
 * @summary Create a new User
 */
export const useCreateUser = <TError = ValidationErrorResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{data: User}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createUser>>,
        TError,
        {data: User},
        TContext
      > => {

      const mutationOptions = getCreateUserMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Retrieve a User by its ID
 * @summary Get a specific User
 */
export const getUserById = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return fetchData<GetUserResponse200>(
      {url: `/api/User/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getGetUserByIdQueryKey = (id?: number,) => {
    return [`/api/User/${id}`] as const;
    }

    
export const getGetUserByIdQueryOptions = <TData = Awaited<ReturnType<typeof getUserById>>, TError = null>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserById>>> = ({ signal }) => getUserById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getUserById>>>
export type GetUserByIdQueryError = null


export function useGetUserById<TData = Awaited<ReturnType<typeof getUserById>>, TError = null>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserById>>,
          TError,
          Awaited<ReturnType<typeof getUserById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserById<TData = Awaited<ReturnType<typeof getUserById>>, TError = null>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserById>>,
          TError,
          Awaited<ReturnType<typeof getUserById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserById<TData = Awaited<ReturnType<typeof getUserById>>, TError = null>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a specific User
 */

export function useGetUserById<TData = Awaited<ReturnType<typeof getUserById>>, TError = null>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserByIdQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Update an existing User with the provided details
 * @summary Update a User
 */
export const updateUser = (
    id: number,
    user: User,
 ) => {
      
      
      return fetchData<UpdateUserResponse200>(
      {url: `/api/User/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: user
    },
      );
    }
  


export const getUpdateUserMutationOptions = <TError = NotFoundResponse | ValidationErrorResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{id: number;data: User}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{id: number;data: User}, TContext> => {

const mutationKey = ['updateUser'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUser>>, {id: number;data: User}> = (props) => {
          const {id,data} = props ?? {};

          return  updateUser(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUserMutationResult = NonNullable<Awaited<ReturnType<typeof updateUser>>>
    export type UpdateUserMutationBody = User
    export type UpdateUserMutationError = NotFoundResponse | ValidationErrorResponse | InternalServerErrorResponse

    /**
 * @summary Update a User
 */
export const useUpdateUser = <TError = NotFoundResponse | ValidationErrorResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{id: number;data: User}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateUser>>,
        TError,
        {id: number;data: User},
        TContext
      > => {

      const mutationOptions = getUpdateUserMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Delete a User by its ID
 * @summary Delete a User
 */
export const deleteUser = (
    id: number,
 ) => {
      
      
      return fetchData<DeleteUserResponse200>(
      {url: `/api/User/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteUserMutationOptions = <TError = NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteUser'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUser>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteUser(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUser>>>
    
    export type DeleteUserMutationError = NotFoundResponse | InternalServerErrorResponse

    /**
 * @summary Delete a User
 */
export const useDeleteUser = <TError = NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUser>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteUserMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
